config/routes.rb
Rails.application.routes.draw do

 resource :user_session, :only => [:new, :create, :destroy]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :committees_voivodships

  resources :committees_districts

  resources :voivodships

  resources :districts

  resources :committees

  resources :users

  root :to => 'static#index'
  resource :user_session, :only => [:new, :create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  get '/central', :controller => 'static', :action => 'central'
  get '/role_district', :controller => 'static', :action => 'district'
  get '/invalid', :controller => 'committees_voivodships', :action => 'invalid'
  get '/all_districts', :controller => 'committees_districts', :action => 'all'
  
  get '/votes_voivodships', :controller => 'committees_voivodships', :action => 'full'
  get '/percentage_voivodships', :controller => 'committees_voivodships', :action => 'turnout'
  get '/percentage_districts', :controller => 'committees_voivodships', :action => 'percentage'
 
  get '/results', :controller => 'committees_voivodships', :action => 'results'

end

app/models/committees_district.rb
class CommitteesDistrict < ActiveRecord::Base
  belongs_to :committee
  belongs_to :district
  belongs_to :voivodship
 
  validate :nowsze
  validate :nowe
  def nowsze
	@cards = District.all.where("id = ?", self.district_id)
	@alls = CommitteesDistrict.all.where("district_id = ?", self.district_id).where("committee_id != ?", self.committee_id).group("district_id").sum("votes")

	@alls.each do |all|
	@cards.each do |card|

		if self.votes != nil
			if self.votes > card.valid_votes - all[1]
	  		errors.add(:base, 'Sum of votes is higher than number of valid votes')
			end
		end
	end
   end
 end
  def nowe
	@cards = District.all.where("id = ?", self.district_id)
	@cards.each do |card|
	if self.votes != nil
	  if self.votes > card.vote_cards
	    errors.add(:base, 'Number of votes is to high (more votes than vote cards)')
	  end
	end
	end
  end

  validates :district_id, uniqueness: {scope: :committee_id}
 
  validates :votes, numericality: { only_integer: true, greater_than: -1, allow_blank: true}
 
end

app/controllers/committees_districts_controller.rb
class CommitteesDistrictsController < ApplicationController
  before_action :set_committees_district, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /committees_districts
  # GET /committees_districts.json

  def all
    @committees_districts = CommitteesDistrict.joins(:voivodship).all.where("votes is not null").order("voivodships.name")
  end

  def index
   # @committees_districts = CommitteesDistrict.all
  #end
    @user = current_user
    @committees_districts = CommitteesDistrict.all.where("committees_districts.district_id = ?", current_user.district_id)
   
  end	

  # GET /committees_districts/1
  # GET /committees_districts/1.json
  def show
  end

  # GET /committees_districts/new
  def new
    @committees_district = CommitteesDistrict.new
  end

  # GET /committees_districts/1/edit
  def edit
  end

  # POST /committees_districts
  # POST /committees_districts.json
  def create
    @committees_district = CommitteesDistrict.new(committees_district_params)

    respond_to do |format|
      if @committees_district.save
        format.html { redirect_to @committees_district, notice: 'Committees district was successfully created.' }
        format.json { render :show, status: :created, location: @committees_district }
      else
        format.html { render :new }
        format.json { render json: @committees_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees_districts/1
  # PATCH/PUT /committees_districts/1.json
  def update
    respond_to do |format|
      if @committees_district.update(committees_district_params)
        format.html { redirect_to @committees_district, notice: 'Committees district was successfully updated.' }
        format.json { render :show, status: :ok, location: @committees_district }
      else
        format.html { render :edit }
        format.json { render json: @committees_district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees_districts/1
  # DELETE /committees_districts/1.json
  def destroy
    @committees_district.destroy
    respond_to do |format|
      format.html { redirect_to committees_districts_url, notice: 'Committees district was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committees_district
      @committees_district = CommitteesDistrict.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committees_district_params
      params.require(:committees_district).permit(:votes)
    end
end

app/helpers/committees_districts_helper.rb
module CommitteesDistrictsHelper
end

app/views/committees_districts/_form.html.erb
<%= form_for(@committees_district) do |f| %>
  <% if @committees_district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committees_district.errors.count, "error") %> prohibited this committees_district from being saved:</h2>

      <ul>
      <% @committees_district.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :oddane_głosy %><br>
	<div class="col-sm-2">
    	<%= f.number_field :votes, :class => 'form-control' %>
	</div>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz" %>
  </div>
<% end %>

app/views/committees_districts/all.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Okręg</th>	
      <th>Województwo</th>
      <th>Komitet</th>	
      <th>Liczba oddanych głosów</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees_districts.each do |committees_district| %>
      <tr>
	<td><%= committees_district.district.name %></td>
	<td><%= committees_district.district.voivodship.name %></td>
	<td><%= committees_district.committee.name %></td>
        <td><%= committees_district.votes %></td>
   
        
      </tr>
    <% end %>
  </tbody>
</table>
<p><a href="votes_voivodships">Zestawienia wojewódzkie</a></p>
<p><a href="/central">Menu - komisja centralna</a></p>
<br>

app/views/committees_districts/edit.html.erb
<h2><%= @committees_district.committee.name %>, okręg <%= @committees_district.district.name %></h2>

<%= render 'form' %>

<%= link_to 'Zobacz', @committees_district %> |
<%= link_to 'Powrót', committees_districts_path %>

app/views/committees_districts/index.html.erb
<h1>Wyniki komitetów w okręgu <%= current_user.district.name %> <%= current_user.district.voivodship.name %>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Komitet</th>	
      <th>Liczba oddanych głosów</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees_districts.each do |committees_district| %>
      <tr>
	<td><%= committees_district.committee.name %></td>
        <td><%= committees_district.votes %></td>
        <td><%= link_to 'Zaktualizuj', edit_committees_district_path(committees_district) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<a href="districts">Ogólne informacje o okręgu</a>
<br>

app/views/committees_districts/new.html.erb
<h1>New committees_district</h1>

<%= render 'form' %>

<%= link_to 'Back', committees_districts_path %>

app/views/committees_districts/show.html.erb
<p id="notice"><%= notice %></p>
<h4><%= @committees_district.committee.name %><br><br>
okręg <%= @committees_district.district.name %>
województwo <%= @committees_district.district.voivodship.name %></h4>
<p>
  <strong>Liczba oddanych głosów:</strong>
  <%= @committees_district.votes %>
</p>

<%= link_to 'Zaktualizuj', edit_committees_district_path(@committees_district) %> |
<%= link_to 'Powrót', committees_districts_path %>